# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cloglik <- function(spec, pset, gdiff = FALSE, dogradient = FALSE, dofisher = FALSE, nthreads = 1L) {
    .Call(`_durmod_cloglik`, spec, pset, gdiff, dogradient, dofisher, nthreads)
}

